backend:
  name: github
  repo: AFGZGZ/new-seoul-indies-project # Replace with your actual GitHub username/repo
  branch: main
  base_url: https://siauth.axeldevelops.workers.dev/ # Your Worker URL
  auth_endpoint: auth # Points to your /auth route

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "games"
    label: "Games Directory"
    folder: "src/content/games"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "blog"
    label: "Blog Posts"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
