backend:
  name: github
  repo: AFGZGZ/new-seoul-indies-project # Replace with your actual GitHub username/repo
  branch: main
  base_url: https://siauth.axeldevelops.workers.dev/ # Your Worker URL
  auth_endpoint: auth # Points to your /auth route

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "src/content/posts"
    create: true
    slug: "{{slug}}"
    extension: "md"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Excerpt", name: "excerpt", widget: "text", required: false }
      - {
          label: "Publish Date",
          name: "publishDate",
          widget: "datetime",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "games"
    label: "Games Directory"
    folder: "src/content/games"
    create: true
    slug: "{{slug}}"
    extension: "md"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Developer", name: "developer", widget: "string" }
      - { label: "Status", name: "status", widget: "string" }
      - {
          label: "Cover Image",
          name: "cover",
          widget: "image",
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }
